In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

### Simple Classifier for XOR

In [3]:
class SimpleClassifier(nn.Module):

    def __init__(self, num_inputs, num_hidden, num_outputs):
        # call initializer(constructor) of the nn.Module class
        super().__init__()

        # create the first linear layer of the network
        # applied transformation: y = xA^T + b
        # x - input, A - weight matrix, b - bias, y - output
        self.linear1 = nn.Linear(num_inputs, num_hidden)

        # create the second linear layer of the network
        # similar linear transformation is applied 
        self.linear2 = nn.Linear(num_hidden, num_outputs)

        # implement the activation function using nn.Tanh
        self.act_fn = nn.Tanh()

        
    def forward(self, x):
        # Perform the calculation of the model to determine the prediction

        x = self.linear1(x)
        x = self.act_fn(x)
        x = self.linear2(x)

        return x


In [4]:
model = SimpleClassifier(num_inputs = 2, num_hidden = 4, num_outputs = 1)
# Printing a module shows all its submodules
print(model)

SimpleClassifier(
  (linear1): Linear(in_features=2, out_features=4, bias=True)
  (linear2): Linear(in_features=4, out_features=1, bias=True)
  (act_fn): Tanh()
)


In [13]:
# Obtain the parameters of the model with parameter() function
for parameter in model.parameters():
    print(f'Shape: {parameter.shape}\n{parameter}\n')

Shape: torch.Size([4, 2])
Parameter containing:
tensor([[ 0.4806,  0.6963],
        [ 0.6889,  0.6176],
        [ 0.3426, -0.1548],
        [ 0.4930, -0.6682]], requires_grad=True)

Shape: torch.Size([4])
Parameter containing:
tensor([ 0.5975,  0.2445, -0.5151, -0.7012], requires_grad=True)

Shape: torch.Size([1, 4])
Parameter containing:
tensor([[0.4025, 0.0348, 0.4953, 0.3293]], requires_grad=True)

Shape: torch.Size([1])
Parameter containing:
tensor([0.3301], requires_grad=True)



In [15]:
# Obtain a name to each parameter object with named_parameters
for name, parameter in model.named_parameters():
    print(f'Parameter: {name}\nShape: {parameter.shape}\n')

Parameter: linear1.weight
Shape: torch.Size([4, 2])

Parameter: linear1.bias
Shape: torch.Size([4])

Parameter: linear2.weight
Shape: torch.Size([1, 4])

Parameter: linear2.bias
Shape: torch.Size([1])

